version: "3.6"
services:
      
  elasticsearch:
    #image: elasticsearch:5.6.11
    #note that the docker hub version doesn't allow restores for some reason...
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    ports:
      - 9200:9200
    environment:
      # assign more memory to JVM 
      - "ES_JAVA_OPTS=-Xms12g -Xmx12g"
      - "xpack.security.enabled=false"
      - "bootstrap.memory_lock=true"
      #allow downloading from open targets google buckets
      - repositories.url.allowed_urls=https://storage.googleapis.com/open-targets-data-releases/*,https://*.amazonaws.com/*
    volumes:
      #use a volume for persistence / performance
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 30s
      timeout: 500s
      retries:  30
        
  kibana:
    image: kibana:5.6.11
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch

  mrtarget:
    build:
      context: ./
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_NODES=http://elasticsearch:9200

volumes:
  esdata:
    driver: local
