version: 2
jobs:
  build:
    working_directory: ~/mrtarget
    docker:
      - image: circleci/python:2.7
    environment:
      - CTTV_MINIMAL=True
    steps:
      - checkout
      - run:
          command: |
            apt-get install -y gzip
      - restore_cache:
         key: mrt-py27-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install requirements.txt
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -U --no-cache-dir -r requirements.txt
            pip uninstall -y requests
            pip install requests
      - save_cache:
          key: mrt-py27-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Dry run to check imports
          command: |
            . venv/bin/activate
            mrtarget --dry-run
      - setup_remote_docker:
          reusable: true    # this allows caching, but may become a premium feature
          exclusive: true
      - run:
          name: Build Docker image
          command: |
            export NAME="mrtarget-circle-${CIRCLE_SHA1}"
            docker build -t $NAME .
      - run:
          name: Push to Quay
          command: |
            docker login -u="opentargets+quaybot" -p="${QUAYBOT_PASSWORD}" quay.io
            docker tag $NAME ${QUAY_REPO}:${CIRCLE_BRANCH}
            [ "$CIRCLE_BRANCH" = "master" ] && docker tag $NAME ${QUAY_REPO}:latest
            docker tag $NAME ${QUAY_REPO}:$NAME
            docker push ${QUAY_REPO}:$NAME
      - run:
          name: Push to GCR
          command: |
            docker login -u _json_key -p $GCR_JSON_KEY_FILE https://eu.gcr.io
            docker tag $NAME ${GCR_REPO}:${CIRCLE_BRANCH}
            [ "$CIRCLE_BRANCH" = "master" ] && docker tag $NAME ${GCR_REPO}:latest
            docker tag $NAME ${GCR_REPO}:$NAME
            docker push ${GCR_REPO}:$NAME

# this could in theory work, but we need to persist the image somewhere
# also we need to pay for > 1 container at the same time
# workflows:
#   version: 2
#   build_and_push:
#     jobs:
#       - build
#       - push_quay:
#           requires:
#             - build
#       - push_gcr:
#           requires:
#             - build

