version: 2
jobs:
  build:
    working_directory: ~/mrtarget
    docker:
      - image: python:2.7
    environment:
      - CTTV_MINIMAL=True
    steps:
      - checkout
      - restore_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install requirements.txt
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -U --no-cache-dir -r requirements.txt
            pip uninstall -y requests
            pip install requests
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Dry run to check imports
          command: |
            . venv/bin/activate
            mrtarget --dry-run
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            TAG="circle-${CIRCLE_BUILD_NUM}"
            docker build -t eu.gcr.io/open-targets/mrtarget:$TAG .
            docker login -u _json_key -p $GCR_JSON_KEY https://eu.gcr.io
            docker push eu.gcr.io/open-targets/mrtarget:$TAG

#       - store_artifacts:
#           path: /tmp/test-results
#           destination: raw-test-output

#       - store_test_results:
#           path: /tmp/test-results
