version: 2
jobs:
  build:
    working_directory: ~/mrtarget
    docker:
      - image: quay.io/opentargets/mrtarget_base:latest
    steps:
      - checkout
      #- restore_cache:
      #   key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
      #- save_cache:
      #    key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m mrtarget.CommandLine --dry-run



#       - setup_remote_docker

#       # This should go into custom primary image, here's only for the sake of explanation
#       - run:
#           name: Install Docker client
#           command: |
#             set -x
#             VER="17.03.0-ce"
#             curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#             tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#             mv /tmp/docker/* /usr/bin

#       - run:
#           name: Build and push Docker image
#           command: |
#             TAG="0.1.${CIRCLE_BUILD_NUM}"
#             docker build -t circleci/cci-demo-docker:$TAG .
#             docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
#             docker push circleci/cci-demo-docker:$TAG

#       - store_artifacts:
#           path: /tmp/test-results
#           destination: raw-test-output

#       - store_test_results:
#           path: /tmp/test-results
